require "spec"

require "../../src/readonly_wrapper.cr"
require "../../src/iterators/*"
require "../../src/multi_indexable/tiling_lex_iterator.cr"
require "../../src/range_syntax"
require "../../src/index_region"
require "../../src/multi_indexable"
require "../../src/multi_indexable/*"
require "../../src/multi_writable"
require "../../src/buffered/**"
require "../../src/n_array"

require "../../src/type_aliases"
require "../../src/exceptions/*"